GET  https://grkgn8fd52.execute-api.ap-southeast-1.amazonaws.com/prod/spaces
###
POST  https://grkgn8fd52.execute-api.ap-southeast-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
    "location": "Macau",
    "name": "PATCH Test"
}
###
GET https://grkgn8fd52.execute-api.ap-southeast-1.amazonaws.com/prod/spaces?id=29e88412-b57a-47df-8eb6-f30b4c598097
###
PUT  https://grkgn8fd52.execute-api.ap-southeast-1.amazonaws.com/prod/spaces?id=29e88412-b57a-47df-8eb6-f30b4c598097
Content-Type: application/json

{
    "name": "Neighbor of Hong Kong",    
    "location": "Macau"
}
###
DELETE https://grkgn8fd52.execute-api.ap-southeast-1.amazonaws.com/prod/spaces?id=29e88412-b57a-47df-8eb6-f30b4c598097