GET  https://grkgn8fd52.execute-api.ap-southeast-1.amazonaws.com/prod/spaces
###
POST  https://grkgn8fd52.execute-api.ap-southeast-1.amazonaws.com/prod/spaces
content-type: application/json

{
    "location": "Hong Kong"
}
###
GET https://grkgn8fd52.execute-api.ap-southeast-1.amazonaws.com/prod/spaces?id=7f3214a2-c506-4aca-8149-72ef869dfc8c
###
PUT  https://grkgn8fd52.execute-api.ap-southeast-1.amazonaws.com/prod/spaces?id=7f3214a2-c506-4aca-8149-72ef869dfc8c
content-type: application/json

{
    
    "location": "Macau"
}
###
DELETE https://grkgn8fd52.execute-api.ap-southeast-1.amazonaws.com/prod/spaces?id=0d0464c8-fdb2-4a7a-9142-b3a78993bfcf